version: '1.0'

services:
  portal:
    build: ./portal
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database

  flyway:
    image: flyway/flyway:latest
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMAS}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./backend/src/data-etl/1_tables:/flyway/sql
    depends_on:
      - database

  database:
    image: postgres:14
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}