const ActionType = {
    SET_LOADING: 'SET_LOADING',

    SET_PAGE: 'SET_PAGE',
    SET_LIMIT: 'SET_LIMIT',

    GET_CATALOGS: 'GET_CATALOGS',
    GET_BOOKS_BY_CATALOG_ID: 'GET_BOOKS_BY_CATALOG_ID',
    GET_AUTHORS: 'GET_AUTHORS',

    SAVE_BOOK: 'SAVE_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    DELETE_BOOK: 'DELETE_BOOK'
}

export default Object.freeze(ActionType);
